file_to_process: "/Users/chmoulli/Google-Drive/REDHAT/RH-GP/Reports/2016/report/test.adoc"

attributes:
  showtitle: ''
  stylesheet: 'foundation.css'
  stylesdir: 'css'
  nofooter: 'yes'
  linkcss: 'true'

options:
  doctype: 'article'
  header_footer: 'false'
  #to_dir: '/Users/chmoulli/Google-Drive/REDHAT/RH-GP/Reports/2016/generated_content'
  #to_file: 'output.html'
  safe: 'unsafe' # Required to avoid that the file to process is not loaded