file_to_process: "./minutes/test.adoc"

attributes:
  showtitle: ''
  stylesheet: 'foundation.css'
  stylesdir: 'css'
  nofooter: 'yes'
  linkcss: 'true'

options:
  doctype: 'article'
  header_footer: 'true'
  to_dir: 'generated'
  to_file: 'output.html'
  safe: 'unsafe' # Required to avoid that the file to process is not loaded