file_to_process: "./examples/minute.adoc"
file_to_inline: "./generated_content/output.html"
file_inlined: "./generated_content/output-inlined.html"

userName: "First & Last Name"
fromEmail: "user@domain"
toEmail: "user@domain"

# userName: "Charles Moulliard"
# fromEmail: "Charles Moulliard <cmoulliard@redhat.com>"
# toEmail: "cmoulliard@redhat.com"

attributes:
  showtitle: ''
  stylesheet: 'foundation.css'
  stylesdir: 'generated_content/css'
  nofooter: 'yes'
  icons: 'font'
  # linkcss: 'true' # Don't use this option if you want to embed the CSS

options:
  doctype: 'article'
  # header_footer: ''
  to_dir: 'generated_content'
  to_file: 'output.html'
  safe: 'unsafe' # Required to avoid that the file to process is not loaded

