source: "./source" # or could be a directory eg. ./examples
destination: "./generated"

attributes:
  showtitle: ''
  backend: 'revealjs'
  stylesheet: 'foundation.css'
  stylesdir: 'css'
  nofooter: 'yes'
  icons: 'font'
  # linkcss: 'true' # Don't use this option if you want to embed the CSS

options:
  doctype: 'article'
  template_dir: '/path/to/revealjs/jade/templates' # /Users/chmoulli/Temp/asciidoctorjs-slide-templates-master
  to_dir: 'generated'
  to_file: 'output.html'
  safe: 'unsafe' # Required to avoid that the file to process is not loaded

