# source: "./source" # or could be a directory eg. ./examples
source: "./generated_content/hol.html" # or could be a directory eg. ./examples
destination: "./generated"
file_to_inline: "./generated/output.html"
file_inlined: "./generated/output-inlined.html"

userName: "First & Last Name"
fromEmail: "user@domain"
toEmail: "user@domain"

git_repos: ['https://github.com/asciidoctor/asciidoctor-stylesheet-factory.git']

attributes:
  showtitle: ''
  stylesheet: 'foundation.css'
  stylesdir: 'css'
  nofooter: 'yes'
  icons: 'font'
  # linkcss: 'true' # Don't use this option if you want to embed the CSS

options:
  doctype: 'article'
  to_dir: 'generated'
  to_file: 'output.html'
  safe: 'unsafe' # Required to avoid that the file to process is not loaded

#
# PDF Parameters
#
pdf:
  format: A4
  orientation: portrait
  zoomFactor: "0.55"
  border:
   top: 20px
   right: 15px
   bottom: 20px
   left: 15px
  header:
   height: 5mm
   contents:
    default: "<div style='color: #444; font-size: 80%; text-align: center;'>Author: Litoria</div>"
  footer:
   height: 10mm
   contents:
    2: "Second page"
    first: "Cover page"
    default: "<div style='color: #444; font-size: 80%; text-align: center;'>{{page}}/{{pages}} - &copy; Litoria - 2016</div>"
    last: "Last Page"
  type: pdf
  quality: 100
  phantomPath: "/Users/chmoulli/MyProjects/litoria/node_modules/phantomjs-prebuilt/bin/phantomjs"

